name: Publish Changes Test
on:
  pull_request_target:
    types:
      - closed
    branches:
      - 'main'
    paths:
      - 'test_folder/test_file.js'

jobs:
  promoted:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
        echo "The title of you PR is ${{ github.event.pull_request.title}}"
        echo "The body of you PR is ${{ github.event.pull_request.body}}"
        echo "End"
