name: Publish Changes Test
on:
  pull_request_target:
    types:
      - closed
    branches:
      - 'main'

jobs:
  promoted:
    if: |
      (
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'Promote') &&
      contains(github.event.pull_request.labels.*.name, 'from dev1 to prod1')
      )
    runs-on: ubuntu-latest
    steps:
    - name: PR Merged
      run: |
        echo The PR was merged: ${{ github.event.pull_request.title}}"
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: githubchangelog
        SLACK_TITLE: ${{ github.event.pull_request.title}}
        SLACK_MESSAGE: ${{ github.event.pull_request.body}}
