name: Publish Changes Test
on:
  pull_request_target:
    types:
      - closed
    branches:
      - 'test-branch'
    paths:
      - 'test_folder/test_file.js'

jobs:
  if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'promote') 
  runs-on: ubuntu-latest
  steps:
  - run: |
      echo The PR was merged
      echo "The title of you PR is ${{ github.event.pull_request.title}}"
      echo "The body of you PR is ${{ github.event.pull_request.body}}"
      echo "End"
