name: Push branch

on:
  push:
    branches:
      - 'test-branch'

jobs:
  pushed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0    
    - name: Echo messages 
      run: |
        output=$( python scripts/save_formated_pr_body.py ${{ github.event.pull_request.body}} )
        echo "::set-output name=content::$PR_BODY"
      id: pr_body
    - name: Print pr
      run: echo "${{ steps.pr_body.outputs.content }}"
