name: Push branch

on:
  push:
    branches:
      - 'test-branch'

jobs:
  pushed:
    runs-on: ubuntu-latest
    steps:
    - name: Echo messages 
      run: |
        PR_BODY=${{ github.event.pull_request.body}}
        echo "::set-output name=content::$PR_BODY"
      id: pr_body
    - name: Print pr
      run: echo "${{ steps.pr_body.outputs.content }}"
